### ISSUE TITLE
License

### ISSUE THREAD

**Issue by PhilJbt** [zeolan/digital-ocean-app#1]
Could you please tell under which license this repository is?
Especially the file [data.json](https://github.com/zeolan/digital-ocean-app/blob/main/src/data.json).

**Comment by zeolan** [comment]
File data.json is created by me. Actually, this is my app data, because I don't use any database.

**Comment by PhilJbt** [comment]
I am interested in this file for a project. But for me to be able to use it, the license would have to be officially determined in the repository, for legal reasons.

**Comment by zeolan** [comment]
For what purpose do you need this file?

**Comment by PhilJbt** [comment]
I'm looking for a Ukrainian list of verbs for a small online free game.

**Comment by zeolan** [comment]
Ok. You can use this file, but please keep in mind - these are Russian verbs, Ukrainian version of the app isn't ready yet.
I also updated license in the package.json file, please check.

**Comment by PhilJbt** [comment]
Oh, thanks to point this out! I confused Romanian with Ukrainian.
The update is perfect, thank you. I'll take a look when the Ukrainian version is ready!
